// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qBgQV3ksXJgLCunAYThMki2qW2vEZ_c',
    appId: '1:85403299052:web:8d924060fe017261b449c9',
    messagingSenderId: '85403299052',
    projectId: 'flutter-pratica-cripto',
    authDomain: 'flutter-pratica-cripto.firebaseapp.com',
    storageBucket: 'flutter-pratica-cripto.appspot.com',
    measurementId: 'G-YL1G5WMMG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFhe1kbotpNh7LxICQsjH9t58gGyThDuM',
    appId: '1:85403299052:android:9536cdd0f23a17deb449c9',
    messagingSenderId: '85403299052',
    projectId: 'flutter-pratica-cripto',
    storageBucket: 'flutter-pratica-cripto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rcX0qL22fKubfowdVoAPQ3cBynrxE4E',
    appId: '1:85403299052:ios:408359589f81095bb449c9',
    messagingSenderId: '85403299052',
    projectId: 'flutter-pratica-cripto',
    storageBucket: 'flutter-pratica-cripto.appspot.com',
    iosClientId: '85403299052-9hetm4she4n9och4ntqpfhgutjtl97eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.aula04FlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4rcX0qL22fKubfowdVoAPQ3cBynrxE4E',
    appId: '1:85403299052:ios:1583d3dc0b058696b449c9',
    messagingSenderId: '85403299052',
    projectId: 'flutter-pratica-cripto',
    storageBucket: 'flutter-pratica-cripto.appspot.com',
    iosClientId: '85403299052-hgbv5ac15gj4d85ugb2k98eklkt78e5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.aula04FlutterApp.RunnerTests',
  );
}
